### PR TITLE
docs(README.md): add 'Welcome to atelier-pr' in README.md

### PR DESCRIPTION
**Pull request by MrLkuch**

### CODE REVIEW

**Review by RenaudBaussart — CHANGES_REQUESTED** [review]
this lign is already taken find a other one plz

**Review by Nicolas-Puchois — CHANGES_REQUESTED** [review]
Gère les conflits avant de pull request

**Comment by MrLkuch** [comment]
I changed my code. @RenaudBaussart

**Review by Hugo-walando — APPROVED** [review]

**Review by Nicolas-Puchois — APPROVED** [review]
merge issue corrected, approve

**Review by Nicolas-Puchois — CHANGES_REQUESTED** [review]
merge issues (again)

**Review by RenaudBaussart — APPROVED** [review]

**Pull request merged**
